config/routes.rb
# frozen_string_literal: true

# routes
Rails.application.routes.draw do
  mount ShoppingCart::Engine => '/shopping_cart', as: 'shopping_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get '/', to: 'home#index'

  scope '/:locale', locale: /en|ru/ do
    root to: 'home#index'

    get 'cart', to: 'cart#index'
    delete 'cart', to: 'cart#destroy'
    post 'cart_item', to: 'cart#add_item'
    put 'cart_decrement_item', to: 'cart#decrement'
    put 'cart_increment_item', to: 'cart#increment'

    resources :customer, only: %i[index]
    put 'customer/login', to: 'customer#login'
    post 'customer/register', to: 'customer#register'

    resources :checkout
    resources :categories, only: %i[index show]
    resources :home, only: %i[index]
    resources :orders, only: %i[index show] do
      get '/confirm/:token', to: 'orders#confirm', as: 'confirm'
    end
    resources :books, only: :show do
      resources :reviews, only: :create
    end
    resources :addresses, only: %i[index create update]
    resources :coupons, only: :create
  end
end

app/models/ability.rb
# frozen_string_literal: true

# Ability
class Ability
  include CanCan::Ability

  # def initialize(user)
  #   user ||= User.new

  #   can :read, :all
  #   can %i[read create update confirm], Order, user_id: user.id
  #   can :read, [Author, Book, Category, Review]
  #   can %i[read create update], Delivery
  #   can %i[read create update], CreditCard, user_id: user.id
  #   can %i[read create update], Address, addressable_type: 'User',
  #                                        addressable_id: user.id

  #   return unless user.confirmed_at
  #   can :create, Review, user_id: user.id

  #   return unless user.admin
  #   can :access, :rails_admin
  #   can :dashboard
  #   can :manage, :all
  # end

  def initialize(user)
    user ||= User.new

    can :read, :all

    if user.admin
      init_admin_ability
    elsif user.confirmed_at
      init_confirmed_user_ability(user)
    end
  end

  def init_admin_ability
    can :access, :rails_admin
    can :manage, :all
  end

  def init_confirmed_user_ability(user)
    can :create, Review, user_id: user.id
    can %i[create update], Address, addressable_type: 'User',
                                    addressable_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

# Book
class Book < ApplicationRecord
  FILTERS = %i[newest popular price_asc price_desc
               by_title_asc by_title_desc].freeze

  DEFAULT_FILTER = :newest
  PER_PAGE = 5
  CURRENT_PAGE = 1

  has_many :images, dependent: :destroy
  belongs_to :category
  has_and_belongs_to_many :authors
  has_many :positions, class_name: 'ShoppingCart::Position'
  has_many :orders, through: :positions, dependent: :destroy, class_name: 'ShoppingCart::Order'
  has_many :reviews, dependent: :destroy

  validates :title, :price, :materials, presence: true
  validates :height, :width, :depth,
            numericality: { greater_than_or_equal_to: 0 }
  validates :publication_year,
            numericality: { less_than_or_equal_to: Time.current.year }

  scope :for_slider, -> { order(:created_at).last(3) }
  scope :newest, -> { order(created_at: :desc) }
  scope :price_asc, -> { order(:price) }
  scope :price_desc, -> { order(price: :desc) }
  scope :by_title_asc, -> { order(:title) }
  scope :by_title_desc, -> { order(title: :desc) }

  scope :best_sellers, (lambda do
    left_outer_joins(:positions)
    .select('books.*, COUNT(shopping_cart_positions) as count')
    .group('books.id')
    .order('count desc')
    .limit 4
  end)

  scope :popular, (lambda do
    left_outer_joins(:positions)
    .group('books.id')
    .order('COALESCE(SUM(shopping_cart_positions.quantity), 0) desc')
  end)

  scope :by_filter, (lambda do |filter, page|
    public_send(filter).page(CURRENT_PAGE).per(PER_PAGE * page)
  end)
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:facebook]

  has_many :orders, dependent: :destroy, class_name: 'ShoppingCart::Order'
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def self.new_with_session(params, session)
    super.tap do |user|
      data = session['devise.facebook_data'] &&
             session['devise.facebook_data']['extra']['raw_info']
      if data
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.image = auth.info.image
      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  include Locale
  protect_from_forgery with: :exception
  before_action :present_order, :set_locale

  [CanCan::AccessDenied, ActiveRecord::RecordNotFound,
   ActionController::RoutingError].each do |error|
    rescue_from error do |exception|
      redirect_to main_app.root_path, alert: exception.message
    end
  end

  def present_order
    @last_order ||= order_from_current_user || order_from_session
    return unless @last_order.nil? || !@last_order.in_progress?
    @last_order = new_order
  end

  def current_order
    @last_order
  end

  private

  def order_from_current_user
    order = current_user&.orders&.find_by(state: 'in_progress')
    session[:order_id] = order.id if order
    order
  end

  def order_from_session
    ShoppingCart::Order.find_by(id: session[:order_id])
  end

  def new_order
    tracking_number = "R#{Time.now.strftime('%d%m%y%H%M%S')}"
    order = ShoppingCart::Order.create(user: current_user, tracking_number: tracking_number)
    session[:order_id] = order.id
    order
  end
end

app/controllers/customer_controller.rb
# frozen_string_literal: true

# CustomerController
class CustomerController < ApplicationController
  def index; end

  def login
    @user = User.find_by_email(customer_params[:email])
    if @user&.valid_password?(customer_params[:password])
      login_successfully(@user)
    else
      login_unsuccessfully(customer_params[:email])
    end
  end

  def register
    user = new_user
    user.persisted? ? register_successfully(user) : register_unsuccessfully
  end

  private

  def register_successfully(user)
    sign_in(:user, user)
    flash[:success] = t('devise.registrations.signed_up')
    redirect_to shopping_cart.checkout_index_path
  end

  def register_unsuccessfully
    flash[:alert] = t('customer.user_exist')
    redirect_to customer_index_path
  end

  def login_successfully(user)
    sign_in(:user, user)
    flash[:success] = t('devise.sessions.signed_in')
    redirect_to shopping_cart.checkout_index_path
  end

  def login_unsuccessfully(email)
    flash[:alert] = t('devise.failure.not_found_in_database',
                      authentication_keys: email)
    redirect_to customer_index_path
  end

  def new_user
    password = Devise.friendly_token.first(8)
    user = User.create(email: customer_params[:email],
                       password: password,
                       password_confirmation: password,
                       confirmed_at: Time.now.utc)
    user
  end

  def customer_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
  def categories
    Category.all
  end

  def quantity_book_in_cart
    return 0 unless @last_order.in_progress?
    @last_order.books.count
  end

  def qunatity_book_in_category(id)
    Book.where(category_id: id).count
  end
end

app/views/books/show.haml
= link_to :back, class: "general-back-link" do
  %i.fa.fa-long-arrow-left.mr-15
  = t('link.back')
.row
  .col-sm-6
    .product-gallery
      .mb-20
        = cl_image_tag(@book.root_image, class: 'img-responsive')
      .images.clearfix
        - if @book.images.length > 1
          - @book.images.offset(1).last(3).each do |image|
            = link_to '#', class: 'img-link' do
              = cl_image_tag(image.url)
  .col-sm-6
    %h1.mt-res-0= @book.title
    %p.lead.small= @book.authors_names
    .row
      .col-xs-12.col-md-4
        %p.h1.in-gold-500.mt-10= "€#{@book.price}"
      = simple_form_for :items, url: shopping_cart.cart_item_path, method: :post do |f|  
        .col-xs-5.col-md-3
          .input-group.general-position
            %a#decrement-book-quantity.input-link{href: "#"}
              %i.fa.fa-minus.line-height-40
            = f.input :quantity, input_html: { class: 'quantity-input', value: 1 }, label: false, wrapper: false, as: :string
            %a#increment-book-quantity.input-link{href: "#"}
              %i.fa.fa-plus.line-height-40
            = f.hidden_field :book_id, value: @book.id
            = f.hidden_field :price, value: @book.price    
        .col-xs-7.col-md-5
          = f.button :submit, value: t('books.add_to_cart'), class: 'pull-right general-position'
    .general-info-wrap.divider-lg
      %p Description
      %p.lead.small.line-height-2
        = @book.description
        %a.in-gold-500.ml-10{href: "#"}= t('books.read_more')
    .general-info-wrap.divider-lg
      .clearfix
        %p.pull-left= t('books.publication_year')
        %p.lead.small.pull-right= @book.publication_year
    .general-info-wrap.divider-lg
      .clearfix
        %p.pull-left= t('books.dimensions')
        %p.lead.small.pull-right= @book.dimensions
    .general-info-wrap.divider-lg
      .clearfix
        %p.pull-left= t('books.materials')
        %p.lead.small.pull-right= @book.materials
.mb-80
  %h3.in-gold-500.mb-25= "#{t('books.reviews')} (#{@book.reviews.count})" 
  = render 'new_review'
  - @book.reviews.each do |review|
    = render 'review', review: review

app/views/checkout/checkout_complete.haml
%h1.general-title-margin Checkout
%ul.steps.list-inline
  %li.step.done
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs Address
  %li.step-divider
  %li.step
    %span.step-number 2
    %span.step-text.hidden-xs Delivery
  %li.step-divider
  %li.step
    %span.step-number 3
    %span.step-text.hidden-xs Payment
  %li.step-divider
  %li.step
    %span.step-number 4
    %span.step-text.hidden-xs Confirm
  %li.step-divider
  %li.step.active
    %span.step-number 5
    %span.step-text.hidden-xs Complete
.text-center.mb-40
  %h3.general-subtitle Thank You for your Order!
  %p.fw-300 An order confirmation has been has been sent to John Doe0411@gmail.com
.row.mb-20
  .col-sm-6
    .visible-xs
      %p.general-order-number.mb-0 Order #R25314582
      %p.general-address.mb-30 October 29, 2016
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-6.hidden-xs.text-right
    %p.general-order-number.mb-0 Order #R25314582
    %p.general-address.mb-30 October 29, 2016
.visible-xs
  .general-cart-item.divider-lg
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %P.in-grey-600.fw-300 A recipe-based book to help you efficiently create amazing PHP-based applications with Laravel 5.x
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span 1
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
  .general-cart-item.divider-lg.mb-55
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span 1
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600 Book
        %th.col-method
        %th
          %span.in-grey-600 Price
        %th
          %span.in-grey-600 Quantity
        %th
          %span.in-grey-600 Total
    %tbody
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
        %td
          %p.title Android Programming for Beginners
          %p.in-grey-600.fw-300 Maximize the potential of Bootstrap with a collection of real-world site projects for better, faster, more responsive web applications
        %td
          %span.font-16.in-gold-500 €28.50
        %td
          %span.ml-30 1
        %td
          %span.font-16.in-gold-500 €32.90
.text-center.general-text-right
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16 Subtotal:
      %td
        %p.font-16 €117.69
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16 €0.00
    %tr
      %td
        %strong.font-18 Order Total:
      %td
        %strong.font-18 €117.69
.text-center
  %button.btn.btn-default.mb-20 Back to Store

app/views/checkout/checkout_confirm.haml
%h1.general-title-margin Checkout
%ul.steps.list-inline
  %li.step.active
    %span.step-number 1
    %span.step-text.hidden-xs Address
  %li.step-divider
  %li.step
    %span.step-number 2
    %span.step-text.hidden-xs Delivery
  %li.step-divider
  %li.step
    %span.step-number 3
    %span.step-text.hidden-xs Payment
  %li.step-divider
  %li.step
    %span.step-number 4
    %span.step-text.hidden-xs Confirm
  %li.step-divider
  %li.step
    %span.step-number 5
    %span.step-text.hidden-xs Complete
.row.mb-20
  .col-sm-3
    %h3.general-subtitle Shipping Address
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-3
    %h3.general-subtitle Billing Address
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-3
    %h3.general-subtitle Shipments
    %p.general-address
      Delivery Next Day!
      %span.general-edit edit
      %br
      By train
  .col-sm-3
    %h3.general-subtitle Payment Information
    %p.general-address
      ** ** ** 8756
      %span.general-edit edit
      %br
      12/2018
.visible-xs
  .general-cart-item.divider-lg
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %P.in-grey-600.fw-300 A recipe-based book to help you efficiently create amazing PHP-based applications with Laravel 5.x
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span 1
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
  .general-cart-item.divider-lg.mb-55
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          .input-group
            %a.input-link{href: "#"}
              %i.fa.fa-minus.line-heaght-40
            %input.form-control.quantity-input{type: "text"}
            %a.input-link{href: "#"}
              %i.fa.fa-plus.line-heaght-40
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600 Book
        %th.col-method
        %th
          %span.in-grey-600 Price
        %th
          %span.in-grey-600 Quantity
        %th
          %span.in-grey-600 Total
    %tbody
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
        %td
          %p.title Android Programming for Beginners
          %p.in-grey-600.fw-300 Maximize the potential of Bootstrap with a collection of real-world site projects for better, faster, more responsive web applications
        %td
          %span.font-16.in-gold-500 €28.50
        %td
          %span.ml-30 1
        %td
          %span.font-16.in-gold-500 €32.90
.text-center.general-text-right
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16 Subtotal:
      %td
        %p.font-16 €117.69
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16 €0.00
    %tr
      %td
        %strong.font-18 Order Total:
      %td
        %strong.font-18 €117.69
.text-center
  %button.btn.btn-default.mb-20 Place Order

app/views/home/_carousel_book.haml
.item{ class: ( active ? 'active' : '' ) }
  .row
    .col-sm-5
      .general-img-wrap
        = cl_image_tag(book.root_image, class: 'img-shadow general-thumbnail-img')
    .col-sm-7
      .mb-60
        %h1= book.title
        - unless book.description.empty?
          %p.lead= book.description
        %p.lead.small= book.authors_names
        .general-align
          = link_to shopping_cart.cart_item_path(items: {price: book.price, quantity: 1, book_id: book.id}), method: :post do
            %button{class: (book.quantity.zero? ? 'disabled btn' : 'btn btn-primary'), disabled: book.quantity.zero? }= t('home.buy_now')

app/views/shared/_book.haml
.col-xs-6.col-sm-3
  .general-thumb-wrap
    %div{class: 'thumbnail general-thumbnail' + (book.quantity.zero? ? ' disabled' : '')}
      = cl_image_tag(book.root_image, class: 'img-shadow general-thumbnail-img')
      .thumb-hover
        .general-thumb-link-wrap
          = link_to book_path(book.id), class: 'thumb-hover-link eye-show-book-btn' do
            %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
          = link_to shopping_cart.cart_item_path(items: {price: book.price, quantity: 1, book_id: book.id}), method: :post, class: 'thumb-hover-link shopping-cart-buy-btn' do
            %i.fa.fa-shopping-cart.thumb-icon
  .general-thumb-info
    %p.title= book.title
    %p.font-16.in-gold-500= "€#{book.price}"
    %span.divider-sm
    %p.lead.small= book.authors_names

app/views/shared/_header.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand= t('header.brand')
      .navbar-brand
        = link_to "en", url_for( :locale => 'en' ),
          class: ['in-gold-500', ('lead' if params[:locale] == 'en')]
        = link_to "ru", url_for( :locale => 'ru' ),
          class: ['in-gold-500', ('lead' if params[:locale] == 'ru')]
      = link_to shopping_cart.cart_path, id: 'shop-link', class: 'shop-link pull-right visible-xs' do
        %span.shop-icon
          %span.shop-quantity= quantity_book_in_cart
    = link_to shopping_cart.cart_path, class: 'shop-link pull-right hidden-xs' do
      %span.shop-icon
        %span.shop-quantity= quantity_book_in_cart
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li= link_to t('header.home'), root_path
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "#menu", 'aria-expanded': "false", 'aria-controls': "menu"}= t('header.shop')
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
              - categories.each do |item|
                %li= link_to(item.title, main_app.category_path(item.id))
          - if current_user
            %li
              %a{type: "button", 'data-toggle': "collapse", href: "#account", 'aria-expanded': "false", 'aria-controls': "account"}= t('header.account')
              %ul#account.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
                %li= link_to t('header.orders'), shopping_cart.orders_path
                %li= link_to t('header.settings'), main_app.addresses_path
                - if current_user.admin
                  %li= link_to(t('header.admin_panel'), rails_admin_path)  
            %li.divider{role: "separator"}
            %li= link_to t('header.log_out'), main_app.destroy_user_session_path, method: :delete
          - else
            %li.divider{role: "separator"}
            %li= link_to t('header.log_in'), main_app.new_user_session_path
            %li= link_to t('header.sign_up'), main_app.new_user_registration_path
      .hidden-xs
        %ul.nav.navbar-nav
          %li= link_to t('header.home'), root_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}= t('header.shop')
            %ul.dropdown-menu
              - categories.each do |category|
                %li= link_to(category.title, main_app.category_path(category.id))
          - if current_user
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}= t('header.account')
              %ul.dropdown-menu
                %li= link_to(t('header.orders'), shopping_cart.orders_path)
                %li= link_to(t('header.settings'), main_app.addresses_path)
                - if current_user.admin
                  %li= link_to(t('header.admin_panel'), main_app.rails_admin_path) 
                %li.divider{role: "separator"}
                %li= link_to(t('header.log_out'), main_app.destroy_user_session_path, method: :delete)
          - else
            %li= link_to(t('header.log_in'), main_app.new_user_session_path)
            %li= link_to(t('header.sign_up'), main_app.new_user_registration_path)

app/views/shopping_cart/cart/index.haml
%h1.general-title-margin= t('cart.cart')
- if @items.count == 0
  %br
  %h1= t('cart.empty_cart')
  %br
  .text-center
    = link_to t('cart.back_to_store'), main_app.root_path, class: 'btn btn-default mb-20'
- else    
  .visible-xs
    - @items.each do |item|
      .general-cart-item.divider-lg-bottom.mb-30
        = link_to(cart_path(book_id: item.id), method: :delete, class: 'close general-cart-close', 'aria-label': "Close") do
          %span{'aria-hidden': "true", id: 'delete-book-btn'} &times;
        .general-img-wrap-table
          = cl_image_tag(item.decorate.root_image, class: 'cart-img-shadow')
        %p.title= item.decorate.title
        %table.table
          %tr
            %td
              %span.in-grey-600= t('cart.price')
            %td
              %span.font-16.in-gold-500.price= "€#{item.decorate.price}"
          %tr
            %td.vertical-middle
              %span.in-grey-600= t('cart.quantity') 
            %td
              .input-group
                = link_to shopping_cart.cart_decrement_item_path(book_id: item.id), method: :put, class: 'input-link' do
                  %i.fa.fa-minus.line-heaght-40
                %input.form-control.quantity-input{type: "text", value: item.decorate.quantity_in_cart(@order)}
                = link_to shopping_cart.cart_increment_item_path(book_id: item.id), method: :put, class: 'input-link' do
                  %i.fa.fa-plus.line-heaght-40
          %tr
            %td
              %span.in-grey-600= t('cart.subtotal')
            %td
              %span.font-16.in-gold-500.total_price= "€#{item.decorate.total_price(@order)}"
  .hidden-xs
    %table.table.table-hover
      %tr.no-hover
        %th.col-pic.pl-0
          %span.in-grey-600= t('cart.product')
        %th.col-title
        %th.col-price
          %span.in-grey-600= t('cart.price')
        %th.col-quantity
          %span.in-grey-600= t('cart.quantity') 
        %th.col-total
          %span.in-grey-600= t('cart.subtotal')
        %th.col-close
      - @items.each do |item|    
        %tr
          %td
            .general-img-wrap-table
              = cl_image_tag(item.decorate.root_image, class: 'cart-img-shadow pull-left')
          %td
            %p.title= item.decorate.title
          %td
            %span.font-16.in-gold-500= "€#{item.decorate.price}"
          %td
            .input-group
              = link_to shopping_cart.cart_decrement_item_path(book_id: item.id), method: :put, class: 'input-link' do
                %i.fa.fa-minus.line-heaght-40
              %input.form-control.quantity-input{type: "text", value: item.decorate.quantity_in_cart(@order)}
              = link_to shopping_cart.cart_increment_item_path(book_id: item.id), method: :put, class: 'input-link' do
                %i.fa.fa-plus.line-heaght-40
          %td
            %span.font-16.in-gold-500= "€#{item.decorate.total_price(@order)}"
          %td
            = link_to(shopping_cart.cart_path(book_id: item.id), method: :delete, class: 'close general-cart-close', 'aria-label': "Close") do
              %span{'aria-hidden': "true", id: 'delete-book-btn'} &times;
  .general-order-wrap
    .row
      .col-sm-4
        - if @order.coupon
          %h3= t('coupon.used')
        - else
          = render 'coupon'
      = render 'order_summary', order: @order
  - if user_signed_in? && !@order.books.count.zero?
    = link_to shopping_cart.checkout_index_path do
      %button.btn.btn-default.mb-20.hidden-xs.center-block= t('checkout.checkout')
  - else
    = link_to main_app.customer_index_path do
      %button.btn.btn-default.mb-20.hidden-xs.center-block= t('checkout.checkout')